language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get install -qq texinfo
  - sudo apt-get install -qq texlive
  - sudo apt-get install -qq liblzma-dev

before_script:
  - autoreconf -vfi

script:
  - ./configure CPPFLAGS="-DDEBUG_FLAG" --with-octave || { cat config.log; false; }
  - make clean all check || { cat test/test-suite.log; false; }
  - make distcheck

## whitelist
branches:
  only:
    - master
    - next

notifications:
  email:
    - devel@fresse.org
